Calculator created
DiLevchenko/KH-067-QA-02-Levchenko-Diana pull request #3
Opened 2022-07-26 19:05 UTC by DiLevchenko

2022-07-28 20:16 UTC, Hmeliumm requested changes

2022-07-28 20:16 UTC, Hmeliumm commented on projectJava/task2_calculator/src/Calculator_DL.java
> +public class Calculator_DL {
Snake case (_) is bad practice. Please change to CamelCase

2022-07-28 20:16 UTC, Hmeliumm commented on projectJava/task2_calculator/src/Calculator_DL.java
> +
Please remove extra line

2022-07-28 20:16 UTC, Hmeliumm commented on projectJava/task2_calculator/src/Calculator_DL.java
> +
Please remove extra line.
Format code (Ctrl + Alt+L)

2022-08-01 11:47 UTC, Hmeliumm requested changes

2022-08-01 11:47 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +            case '+':
Please move arithmetic operators to constant, in case you are using it more than one time (here and below)

2022-08-01 11:47 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +                System.out.println(num1 + " + " + num2 + " = " + result);
Please try to use printf for such cases: System.out.printf(%f + %f + %f, num1, num2, result) (here and below)

2022-08-01 11:47 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +                repeatLoop = input.next().charAt(0) != 'c';
Please move this condition to while

2022-08-01 11:47 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +        input.close();
Good job!

2022-08-01 21:13 UTC, DiLevchenko commented on projectJava/task2_calculator/src/CalculatorDL.java
> +        input.close();
Thanks)

2022-08-02 07:42 UTC, Hmeliumm requested changes

2022-08-02 07:42 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +        final char add = '+';
Please remember that we write constants all in uppercase (like ADD and so on)

2022-08-02 07:42 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +                System.out.println(e);
If you catch Exception then print stack trace at least in this point

2022-08-02 07:42 UTC, Hmeliumm commented on projectJava/task2_calculator/src/CalculatorDL.java
> +
Remove extra lines

2022-08-02 10:43 UTC, Hmeliumm approved these changes

2022-08-02 10:43 UTC, merged